const assert = require('assert');
const fs = require('fs');
const path = require('path');
const read = relative => fs.readFileSync(path.join(__dirname,relative),'utf8');
const app = read('frontend/src/App.jsx');
const sidebar = read('frontend/src/components/Sidebar.jsx');
const dashboard = read('frontend/src/pages/Dashboard.jsx');
const opportunities = read('frontend/src/pages/Opportunities.jsx');
const detail = read('frontend/src/pages/OpportunityDetail.jsx');
const css = read('frontend/src/index.css');
assert(app.includes('path="/opportunities/:workspaceId"'));
assert(!app.includes('<OpportunityWorkspace />'));
assert(sidebar.includes("location.pathname === '/dashboard'"));
assert(sidebar.includes("location.pathname.startsWith('/opportunities/')"));
assert(sidebar.includes("aria-current={item.active ? 'page'"));
assert(dashboard.includes('/api/opportunity-workspaces/dashboard'));
assert(opportunities.includes('OpportunityList'));
for (const requirement of ['Estimated consultant fee','Estimated client upside','EvidenceAndUncertainty','ContactVerification','ReviewGate','OutreachTransition','ProposalSummary']) assert(detail.includes(requirement), requirement);
assert(css.includes('@media (max-width:360px)'));
assert(css.includes('outline:3px solid'));
assert(css.includes('min-height:44px'));
console.log('Commercial Opportunity Design governed routes, states, navigation, responsive and accessibility source contract: PASS');
