import { useEffect, useMemo, useState } from 'react';
import { useAuth } from '../context/AuthContext';

const stages = ['Candidates', 'Selection', 'Opportunity', 'Offer', 'Conversation', 'Next Action'];
const split = value => value.split(',').map(item => item.trim()).filter(Boolean);
const parse = (value, fallback = []) => { try { return typeof value === 'string' ? JSON.parse(value) : value || fallback; } catch { return fallback; } };
const Field = ({ label, value, onChange, placeholder }) => <label className="block"><span className="text-xs font-black uppercase text-slate-500">{label}</span><input value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} className="mt-1 w-full border rounded-xl px-3 py-2" /></label>;

export default function OpportunityWorkspace() {
  const { getHeaders, token } = useAuth();
  const [leads, setLeads] = useState([]); const [selected, setSelected] = useState([]);
  const [workspace, setWorkspace] = useState(null); const [result, setResult] = useState({});
  const [stage, setStage] = useState(0); const [error, setError] = useState('');
  const [profile, setProfile] = useState({ capabilities: '', constraints: '', geography: '', capacity: '', exclusions: '', disqualifiers: '' });
  const [conversationInput, setConversationInput] = useState({ role: '', adaptation: '' });
  const [actionInput, setActionInput] = useState({ type: 'PURSUE', rationale: '', due_at: '' });
  const request = async (path, options = {}) => { const response = await fetch(path, { ...options, headers: getHeaders() }); const data = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(data?.error || 'Request failed'); return data; };
  useEffect(() => { fetch('/api/leads', { headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) } }).then(r => r.json()).then(setLeads).catch(() => setError('Candidates could not be loaded.')); }, [token]);
  const refresh = async id => { const aggregate = await request(`/api/opportunity-workspaces/${id}`); setResult(value => ({ ...value, aggregate })); return aggregate; };
  const profilePayload = () => ({ service_capabilities: split(profile.capabilities), delivery_constraints: split(profile.constraints), geography: split(profile.geography), capacity: profile.capacity.trim(), exclusions: split(profile.exclusions), disqualifiers: split(profile.disqualifiers) });

  const create = async () => { try { setError(''); const created = await request('/api/opportunity-workspaces', { method: 'POST', body: JSON.stringify({ title: 'Commercial Opportunity Decision', capability_profile: profilePayload() }) }); for (const leadId of selected) await request(`/api/opportunity-workspaces/${created.workspace_id}/candidates`, { method: 'POST', body: JSON.stringify({ lead_id: leadId, comparison_context: 'CURRENT_PIPELINE', evidence_window: new Date().toISOString().slice(0,10) }) }); setWorkspace(created); const evaluation = await request(`/api/opportunity-workspaces/${created.workspace_id}/evaluations`, { method: 'POST', body: JSON.stringify({ expected_version: 0 }) }); setResult({ evaluation }); await refresh(created.workspace_id); setStage(1); } catch (e) { setError(e.message); } };
  const selectionDecision = async decision => { try { const value = await request(`/api/opportunity-workspaces/${workspace.workspace_id}/selection-decision`, { method: 'POST', body: JSON.stringify({ decision, selected_candidate_snapshot_id: decision === 'ACCEPTED' ? result.evaluation.lead_snapshot_id : null, resolution_route: decision === 'CHALLENGED' ? 'REASSESSMENT' : null, rationale: decision === 'ACCEPTED' ? 'Customer accepts the evidence-backed comparison.' : 'Customer requests reassessment before progression.' }) }); setResult(v => ({ ...v, selectionDecision: value })); await refresh(workspace.workspace_id); setStage(decision === 'ACCEPTED' ? 2 : 1); } catch (e) { setError(e.message); } };
  const reassess = async () => { try { await request(`/api/opportunity-workspaces/${workspace.workspace_id}/refresh`, { method: 'POST', body: JSON.stringify({ expected_version: result.evaluation.version, change_explanation: 'Customer challenged the prior selection and requested bounded reassessment.' }) }); const evaluation = await request(`/api/opportunity-workspaces/${workspace.workspace_id}/evaluations`, { method: 'POST', body: JSON.stringify({ expected_version: result.evaluation.version }) }); setResult({ evaluation }); await refresh(workspace.workspace_id); setStage(1); } catch (e) { setError(e.message); } };
  const prepareOffer = async () => { try { const offer = await request(`/api/opportunity-workspaces/${workspace.workspace_id}/offer`, { method: 'POST', body: '{}' }); setResult(v => ({ ...v, offer })); setStage(3); } catch (e) { setError(e.message); } };
  const decideOffer = async decision => { try { const value = await request(`/api/opportunity-workspaces/${workspace.workspace_id}/offer`, { method: 'POST', body: JSON.stringify({ decision, adaptation_text: decision === 'ADAPTED' ? result.offerAdaptation : null, rationale: 'Customer-authored offer decision.' }) }); setResult(v => ({ ...v, offerDecision: value })); } catch (e) { setError(e.message); } };
  const prepareConversation = async () => { try { const conversation = await request(`/api/opportunity-workspaces/${workspace.workspace_id}/conversation`, { method: 'POST', body: JSON.stringify({ target_role_category: conversationInput.role, customer_adaptation: conversationInput.adaptation }) }); setResult(v => ({ ...v, conversation })); setStage(4); } catch (e) { setError(e.message); } };
  const createAction = async () => { try { const action = await request(`/api/opportunity-workspaces/${workspace.workspace_id}/actions`, { method: 'POST', body: JSON.stringify(actionInput) }); setResult(v => ({ ...v, action })); setStage(5); } catch (e) { setError(e.message); } };
  const progressAction = async state => { try { const action = await request(`/api/opportunity-workspaces/${workspace.workspace_id}/actions`, { method: 'PATCH', body: JSON.stringify({ action_id: result.action.action_id, state, outcome_note: result.outcomeNote || null }) }); setResult(v => ({ ...v, action })); await refresh(workspace.workspace_id); } catch (e) { setError(e.message); } };

  const aggregate = result.aggregate; const leadOutcome = result.evaluation?.outcomes.find(item => item.outcome === 'LEAD');
  const leadCandidate = aggregate?.candidates.find(item => item.snapshot_id === result.evaluation?.lead_snapshot_id);
  const leadNodes = useMemo(() => (aggregate?.decision_nodes || []).filter(node => node.candidate_snapshot_id === result.evaluation?.lead_snapshot_id), [aggregate, result.evaluation]);
  return <div className="space-y-6">
    <div><p className="text-emerald-600 font-black uppercase tracking-widest text-xs">Commercial Opportunity Intelligence</p><h1 className="text-3xl font-black text-slate-900">Opportunity Decision Workspace</h1><p className="text-slate-600 mt-2">Make and retain an evidence-backed choice from prospect comparison through commercial action.</p></div>
    <div className="grid grid-cols-2 md:grid-cols-6 gap-2">{stages.map((name, i) => <div key={name} className={`rounded-xl p-3 text-xs font-bold ${i <= stage ? 'bg-emerald-500 text-slate-950' : 'bg-slate-200 text-slate-500'}`}>{i+1}. {name}</div>)}</div>
    {error && <div className="bg-rose-50 border border-rose-200 text-rose-700 p-4 rounded-xl">{error}</div>}
    {!workspace && <><section className="bg-white border rounded-2xl p-6 space-y-4"><h2 className="font-black text-xl">Your capability and boundaries</h2><p className="text-sm text-slate-500">Declare what you can credibly deliver and what must disqualify an opportunity.</p><div className="grid md:grid-cols-2 gap-4"><Field label="Service capabilities" value={profile.capabilities} onChange={v=>setProfile(p=>({...p,capabilities:v}))} placeholder="conversion, accessibility"/><Field label="Delivery constraints" value={profile.constraints} onChange={v=>setProfile(p=>({...p,constraints:v}))} placeholder="project length, technology"/><Field label="Geography" value={profile.geography} onChange={v=>setProfile(p=>({...p,geography:v}))} placeholder="UK, remote"/><Field label="Capacity" value={profile.capacity} onChange={v=>setProfile(p=>({...p,capacity:v}))} placeholder="one new project this month"/><Field label="Exclusions" value={profile.exclusions} onChange={v=>setProfile(p=>({...p,exclusions:v}))} placeholder="excluded sectors"/><Field label="Disqualifiers" value={profile.disqualifiers} onChange={v=>setProfile(p=>({...p,disqualifiers:v}))} placeholder="outside geography, unsupported platform"/></div></section>
    <section className="bg-white border rounded-2xl p-6"><h2 className="font-black text-xl">Choose at least three identifiable prospects</h2><div className="grid md:grid-cols-3 gap-3 mt-4">{leads.map(lead => <label key={lead.id} className="border rounded-xl p-4 flex gap-3"><input type="checkbox" checked={selected.includes(lead.id)} onChange={e => setSelected(v => e.target.checked ? [...v, lead.id] : v.filter(id => id !== lead.id))}/><span><b>{lead.business_name || lead.domain}</b><small className="block text-slate-500">{lead.niche || 'General'} · {lead.opportunity_understanding?.status || 'Evidence unavailable'}</small></span></label>)}</div><button disabled={selected.length < 3 || !profile.capabilities.trim() || !profile.capacity.trim()} onClick={create} className="mt-5 bg-slate-900 disabled:bg-slate-300 text-white rounded-xl px-5 py-3 font-bold">Compare prospects</button></section></>}
    {workspace && <section className="bg-slate-50 border rounded-2xl p-5"><h2 className="font-black">Your declared capability boundary</h2><div className="grid md:grid-cols-3 gap-3 mt-3 text-sm"><p><b>Capabilities:</b> {profile.capabilities || 'None declared'}</p><p><b>Delivery constraints:</b> {profile.constraints || 'None declared'}</p><p><b>Geography:</b> {profile.geography || 'None declared'}</p><p><b>Capacity:</b> {profile.capacity}</p><p><b>Exclusions:</b> {profile.exclusions || 'None declared'}</p><p><b>Disqualifiers:</b> {profile.disqualifiers || 'None declared'}</p></div></section>}
    {result.evaluation && <section className="bg-white border rounded-2xl p-6 space-y-4"><h2 className="font-black text-xl">Who should you approach?</h2><div className="text-2xl font-black">{leadOutcome ? leadOutcome.business_name : 'No responsible winner'}</div><p>{result.evaluation.comparative_explanation}</p><div className="grid md:grid-cols-3 gap-3">{result.evaluation.outcomes.map(item => <div key={item.candidate_snapshot_id} className={`border rounded-xl p-4 ${item.outcome==='LEAD'?'border-emerald-500 bg-emerald-50':''}`}><b>{item.business_name}</b><span className="block text-xs font-black mt-1">{item.outcome}</span><p className="text-sm mt-2">{item.decisive_reason}</p><p className="text-xs text-slate-500 mt-2">Could change if: {item.priority_change_condition}</p><p className="text-xs mt-2">Confidence: {item.confidence_basis}</p><p className="text-xs mt-2">Boundaries: {[...(item.boundary_assessment?.satisfied||[]),...(item.boundary_assessment?.unresolved||[]),...(item.boundary_assessment?.conflicts||[])].join('; ')}</p></div>)}</div>{!result.selectionDecision && leadOutcome && <div className="flex gap-3"><button onClick={()=>selectionDecision('ACCEPTED')} className="bg-emerald-500 rounded-xl px-5 py-3 font-bold">Accept selection</button><button onClick={()=>selectionDecision('CHALLENGED')} className="border rounded-xl px-5 py-3 font-bold">Challenge selection</button></div>}{result.selectionDecision?.decision === 'CHALLENGED' && <div className="bg-amber-50 border border-amber-300 rounded-xl p-4"><b>Selection challenged — progression is paused.</b><p className="text-sm my-2">Reassess after changing inputs or obtaining further evidence. The unchanged recommendation cannot progress.</p><button onClick={reassess} className="border rounded-xl px-4 py-2 font-bold">Reassess current evidence</button></div>}</section>}
    {result.selectionDecision?.decision === 'ACCEPTED' && leadCandidate && <section className="bg-white border rounded-2xl p-6 space-y-4"><h2 className="font-black text-xl">Why this opportunity matters</h2><p className="font-bold">{leadCandidate.subject_identity.business_name}</p><div className="grid md:grid-cols-2 gap-3">{leadNodes.map(node => <div key={node.node_id} className="border rounded-xl p-4"><span className="text-xs font-black text-emerald-700">{node.type.replace('_',' ')}</span><p>{node.statement}</p><small>Confidence: {node.confidence}</small><details className="mt-2 text-xs"><summary>Supporting evidence</summary>{parse(node.evidence_references_json).map(ref=><div key={ref}>{ref}</div>)}{parse(node.assumptions_json).map(item=><div key={item}>Assumption: {item}</div>)}{parse(node.limitations_json).map(item=><div key={item}>Limitation: {item}</div>)}</details></div>)}</div><div className="bg-slate-50 rounded-xl p-4"><b>Contradictions and limitations</b><p>{leadCandidate.contradictions.length ? leadCandidate.contradictions.join('; ') : 'No material contradiction recorded.'}</p><p>{leadCandidate.opportunity_understanding.material_limitations?.join('; ') || 'No additional material limitation.'}</p></div>{!result.offer && <button onClick={prepareOffer} className="bg-emerald-500 rounded-xl px-5 py-3 font-bold">Build capability-fit offer</button>}</section>}
    {result.offer && <section className="bg-white border rounded-2xl p-6 space-y-3"><h2 className="font-black text-xl">What to offer and why</h2><p><b>Offer:</b> {result.offer.primary_service_direction}</p><p><b>Evidence-backed problem:</b> {result.offer.problem_fit}</p><p><b>Plausible qualitative value:</b> {result.offer.intended_qualitative_outcome}</p><p><b>Why first:</b> {result.offer.why_first}</p><p><b>Limitations:</b> {result.offer.limitations?.join('; ') || 'None recorded'}</p><textarea value={result.offerAdaptation || ''} onChange={e=>setResult(v=>({...v,offerAdaptation:e.target.value}))} placeholder="Optional customer adaptation" className="w-full border rounded-xl p-3"/><div className="flex flex-wrap gap-2">{['ACCEPTED','ADAPTED','REJECTED'].map(value=><button key={value} onClick={()=>decideOffer(value)} className="border rounded-xl px-4 py-2 font-bold">{value}</button>)}</div>{result.offerDecision && <div className="text-sm text-emerald-700">Customer decision retained: {result.offerDecision.decision}</div>}</section>}
    {result.offerDecision?.decision === 'REJECTED' && <section className="bg-amber-50 border border-amber-300 rounded-2xl p-5"><b>Offer rejected — conversation progression is paused.</b><p className="text-sm">Accept or adapt an eligible offer before preparing a conversation.</p></section>}
    {['ACCEPTED','ADAPTED'].includes(result.offerDecision?.decision) && <section className="bg-white border rounded-2xl p-6 space-y-4"><h2 className="font-black text-xl">Prepare the conversation</h2><Field label="Role category" value={conversationInput.role} onChange={v=>setConversationInput(p=>({...p,role:v}))} placeholder="Business owner, Marketing director"/><Field label="Your adaptation" value={conversationInput.adaptation} onChange={v=>setConversationInput(p=>({...p,adaptation:v}))} placeholder="Optional customer-authored adjustment"/><button disabled={!conversationInput.role.trim()} onClick={prepareConversation} className="bg-emerald-500 disabled:bg-slate-300 rounded-xl px-5 py-3 font-bold">Prepare conversation</button></section>}
    {result.conversation && <section className="bg-white border rounded-2xl p-6 space-y-2"><h2 className="font-black text-xl">Truthful opening</h2><p><b>Role:</b> {result.conversation.target_role_category}</p><p><b>Observed condition:</b> {result.conversation.observed_condition}</p><p><b>Business relevance:</b> {result.conversation.business_relevance}</p><p><b>Opening question:</b> {result.conversation.bounded_question}</p><p><b>Offer to explore:</b> {result.conversation.offer_to_explore}</p><p><b>Confidence:</b> {result.conversation.confidence_language}</p><p><b>Limitations:</b> {result.conversation.limitations?.join('; ') || 'None recorded'}</p><p><b>Your adaptation:</b> {result.conversation.customer_adaptation || 'No adaptation supplied'}</p></section>}
    {result.conversation && !result.action && <section className="bg-white border rounded-2xl p-6 space-y-4"><h2 className="font-black text-xl">Choose your next commercial action</h2><select value={actionInput.type} onChange={e=>setActionInput(v=>({...v,type:e.target.value}))} className="border rounded-xl px-3 py-2">{['PURSUE','QUALIFY','RESEARCH','DEFER','DECLINE','ARCHIVE'].map(value=><option key={value}>{value}</option>)}</select><Field label="Rationale" value={actionInput.rationale} onChange={v=>setActionInput(p=>({...p,rationale:v}))} placeholder="Why this is the appropriate next action"/><Field label="Due date (optional)" value={actionInput.due_at} onChange={v=>setActionInput(p=>({...p,due_at:v}))} placeholder="YYYY-MM-DD"/><button disabled={!actionInput.rationale.trim()} onClick={createAction} className="bg-emerald-500 disabled:bg-slate-300 rounded-xl px-5 py-3 font-bold">Retain next action</button></section>}
    {result.action && <section className="bg-emerald-50 border border-emerald-200 rounded-2xl p-6 space-y-3"><h2 className="font-black text-xl">Next action retained</h2><p>{result.action.state}: {actionInput.type}</p><textarea value={result.outcomeNote || ''} onChange={e=>setResult(v=>({...v,outcomeNote:e.target.value}))} placeholder="Outcome context" className="w-full border rounded-xl p-3"/><div className="flex gap-2">{result.action.state==='PLANNED' && <button onClick={()=>progressAction('IN_PROGRESS')} className="border rounded-xl px-4 py-2">Start</button>}{!['COMPLETED','CANCELLED'].includes(result.action.state) && <><button onClick={()=>progressAction('COMPLETED')} className="bg-emerald-500 rounded-xl px-4 py-2">Complete</button><button onClick={()=>progressAction('CANCELLED')} className="border rounded-xl px-4 py-2">Cancel</button></>}</div></section>}
  </div>;
}
